name: 'KMP Build iOS App'
description: 'Build and Archive iOS application'
author: 'Mifos Initiative'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  ios_package_name:
    description: 'Name of the Android project module'
    required: true
  firebase_creds:
    description: 'Firebase credentials'
    required: true
  tester_groups:
    description: 'Firebase Tester Group'
    required: true

runs:
  using: composite
  steps:
    # Cache Gradle dependencies to speed up builds
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.konan
          build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    - name: Configure Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        bundler-cache: true

    - name: Install Fastlane
      shell: bash
      run: |
        gem install bundler:2.2.27
        bundle install --jobs 4 --retry 3
        bundle exec fastlane add_plugin firebase_app_distribution
        bundle exec fastlane add_plugin increment_build_number

    - name: Inflate Secrets
      shell: bash
      env:
        GOOGLE_SERVICES: ${{ inputs.google_services }}
        FIREBASE_CREDS: ${{ inputs.firebase_creds }}
      run: |
        mkdir -p secrets
        
        # Inflate Firebase credentials
        touch secrets/firebaseAppDistributionServiceCredentialsFile.json
        echo $FIREBASE_CREDS | base64 --decode > secrets/firebaseAppDistributionServiceCredentialsFile.json

    - name: Upload iOS App to Firebase Distribution
      shell: bash
      run: bundle exec fastlane ios deploy_on_firebase \
        serviceCredsFile:secrets/firebaseAppDistributionServiceCredentialsFile.json \
        groups:${{ inputs.tester_groups }}

    - name: Upload iOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        retention-days: 1
        compression-level: 9
        path: '**/*.ipa'
