name: KMP Build Desktop App
description: 'Build the desktop application for all platforms'
author: 'Mifos Initiative'
branding:
  icon: 'play'
  color: 'orange'

inputs:
  desktop_package_name:
    description: 'Name of the desktop project module'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Java development environment
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'  # Use Zulu distribution of OpenJDK
        java-version: '17'     # Use Java 17 version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Package Desktop App
      shell: bash
      run: ./gradlew packageDistributionForCurrentOS

    # Upload Windows executables and installers
    - name: Upload Windows Apps
      if: runner.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Apps
        path: |
          ./${{ inputs.desktop_package_name }}/build/compose/binaries/main/exe/*.exe
          ./${{ inputs.desktop_package_name }}/build/compose/binaries/main/msi/*.msi

    # Upload Linux package
    - name: Upload Linux App
      if: runner.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: Linux-App
        path: './${{ inputs.desktop_package_name }}/build/compose/binaries/main/deb/*.deb'

    # Upload MacOS package
    - name: Upload MacOS App
      if: runner.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: MacOS-App
        path: './${{ inputs.desktop_package_name }}/build/compose/binaries/main/dmg/*.dmg'