name: KMP Build Desktop App
description: 'Build the desktop application for all platforms'
author: 'Mifos Initiative'
branding:
  icon: 'play'
  color: 'orange'

inputs:
  desktop_package_name:
    description: 'Name of the desktop project module'
    required: true

  build_type:
    description: 'Type of build to perform (Debug or Release)'
    required: false
    default: 'Debug'

outputs:
  windows_exec:
    description: 'Path to Windows executable'
    value: ${{ steps.collect-windows.outputs.windows_exec }}

  windows_inst:
    description: 'Path to Windows installer'
    value: ${{ steps.collect-windows.outputs.windows_inst }}

  linux_app:
    description: 'Path to Linux package'
    value: ${{ steps.collect-linux.outputs.linux_app }}

  macos_app:
    description: 'Path to MacOS package'
    value: ${{ steps.collect-macos.outputs.macos_app }}

runs:
  using: 'composite'
  steps:
    - name: Set up Java development environment
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # Cache Gradle dependencies and build outputs to speed up future builds
    - name: Cache Gradle and build outputs
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Package Desktop App
      shell: bash
      run: |
        # Determine the package command based on build type
        if [[ "${{ inputs.build_type }}" == "Release" ]]; then
          ./gradlew packageReleaseDistributionForCurrentOS
        else
          ./gradlew packageDistributionForCurrentOS
        fi

    - name: Collect Windows Paths
      if: matrix.os == 'windows-latest'
      id: collect-windows
      shell: bash
      run: |
        # Find Windows executables and installers
        windows_exec=$(find . -path "**/*.exe" | grep -E "windows|win" | head -n 1)
        windows_inst=$(find . -path "**/*.msi" | grep -E "windows|win" | head -n 1)
        
        # Output Windows paths
        echo "windows_exec=${windows_exec}" >> $GITHUB_OUTPUT
        echo "windows_inst=${windows_inst}" >> $GITHUB_OUTPUT

    - name: Collect Linux Paths
      if: matrix.os == 'ubuntu-latest'
      id: collect-linux
      shell: bash
      run: |
        # Find Linux package
        linux_app=$(find . -path "**/*.deb" | head -n 1)
        
        # Output Linux paths
        echo "linux_app=${linux_app}" >> $GITHUB_OUTPUT

    - name: Collect MacOS Paths
      if: matrix.os == 'macos-latest'
      id: collect-macos
      shell: bash
      run: |
        # Find MacOS package
        macos_app=$(find . -path "**/*.dmg" | head -n 1)
        
        # Output MacOS paths
        echo "macos_app=${macos_app}" >> $GITHUB_OUTPUT

    # Upload Windows executables
    - name: Upload Windows Apps
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.collect-windows.outputs.windows_exec }}

    # Upload Windows installers
    - name: Upload Windows Apps
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.collect-windows.outputs.windows_inst }}

    # Upload Linux package
    - name: Upload Linux App
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.collect-linux.outputs.linux_app }}

    # Upload MacOS package
    - name: Upload MacOS App
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.collect-macos.outputs.macos_app }}