name: 'Build Android App'
description: 'Build the Android application in Debug mode'
author: 'Mifos Initiative'
branding:
  icon: 'play'
  color: 'orange'

inputs:
  android_package_name:
    description: 'Name of the Android project module'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java development environment
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'  # Use Zulu distribution of OpenJDK
        java-version: '17'     # Use Java 17 version

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    # Cache Gradle dependencies and build outputs to speed up future builds
    - name: Cache Gradle and build outputs
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          build
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Build Android App
      shell: bash
      run: ./gradlew :${{ inputs.android_package_name }}:assembleDebug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: '**/build/outputs/apk/**/*.apk'