name: KMP Android App Publish On Firebase Using Fastlane
description: 'Build and deploy Android app on Firebase App Distribution using fastlane'
author: 'Mifos Initiative'
branding:
  icon: upload-cloud
  color: blue

inputs:
  android_package_name:
    description: 'Name of the Android project module'
    required: true

  keystore_file:
    description: 'Base64 encoded keystore file'
    required: true
  keystore_password:
    description: 'Password for the keystore file'
    required: true
  key_alias:
    description: 'Key alias for the keystore file'
    required: true
  key_password:
    description: 'Password for the key alias'
    required: true

  google_services:
    description: 'Google services JSON file'
    required: true
  firebase_creds:
    description: 'Firebase credentials JSON file'
    required: true

  action_url:
    description: 'Current Action URL'
    required: false


runs:
  using: composite
  steps:
    # Setup Ruby for Fastlane automation
    - name: Configure Ruby
      uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0
      with:
        bundler-cache: true

    # Install Fastlane and required plugins for deployment automation
    - name: Install Fastlane
      shell: bash
      run: |
        gem install bundler:2.2.27
        bundle install --jobs 4 --retry 3
        bundle exec fastlane add_plugin firebase_app_distribution
        bundle exec fastlane add_plugin increment_build_number

    - name: Inflate Secrets
      shell: bash
      env:
        FIREBASE_CREDS: ${{ inputs.firebase_creds }}
      run: |
        mkdir -p ${{ github.workspace }}/secrets
        
        # Inflate google-services.json
        echo $GOOGLE_SERVICES | base64 --decode > ${{ inputs.android_package_name }}/google-services.json
        
        # Inflate Firebase credentials
        touch ${{ github.workspace }}/secrets/firebaseAppDistributionServiceCredentialsFile.json
        echo $FIREBASE_CREDS | base64 --decode > ${{ github.workspace }}/secrets/firebaseAppDistributionServiceCredentialsFile.json

    - name: Build Release Android App
      shell: bash
      env:
        KEYSTORE: ${{ github.workspace }}/secrets/release_keystore.keystore
        KEYSTORE_PASSWORD: ${{ inputs.key_store_password }}
        KEYSTORE_ALIAS: ${{ inputs.key_store_alias }}
        KEYSTORE_ALIAS_PASSWORD: ${{ inputs.key_store_alias_password }}
      run: |
        bundle exec fastlane android assembleReleaseApks \
        storeFile: ${{ env.KEYSTORE }} \
        storePassword: ${{ env.KEYSTORE_PASSWORD }} \
        keyAlias: ${{ env.KEYSTORE_ALIAS }} \
        keyPassword: ${{ env.KEYSTORE_ALIAS_PASSWORD }}

    # Deploy to Firebase App Distribution
    - name: ☁️ Deploy to Firebase
      shell: bash
      run: | 
        bundle exec fastlane android deploy_on_firebase \
        actionUrl: ${{ inputs.action_url }}
