name: KMP Build android app

on:
  workflow_dispatch:
    inputs:
      android_package_name:
        description: 'Name of the Android project module'
        type: string
        required: true
        default: 'mifospay-android'
      build_type:
        description: 'Type of build to perform'
        type: string
        required: false
        default: 'Release'

jobs:
  build_android:
    name: Build Android App
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Android App
        uses: ./.github/actions/build-android-app
        id: build-android
        with:
          android_package_name: ${{ inputs.android_package_name }}
          build_type: ${{ inputs.build_type }}
          google_services: ${{ secrets.GOOGLESERVICES }}
          keystore_file: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
          keystore_password: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
          keystore_alias: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS }}
          keystore_alias_password: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS_PASSWORD }}
