name: KMP build desktop app

on:
  workflow_dispatch:

jobs:
  build_desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Desktop App
        uses: ./.github/actions/build-desktop-app
        id: build-desktop
        with:
          desktop_package_name: 'mifospay-desktop'

      - name: Display Desktop App Paths
        run: |
          echo "Windows Exec: ${{ steps.build-desktop.outputs.windows_exec }}"
          echo "Windows Installer: ${{ steps.build-desktop.outputs.windows_inst }}"
          echo "Linux App: ${{ steps.build-desktop.outputs.linux_app }}"
          echo "MacOS App: ${{ steps.build-desktop.outputs.macos_app }}"
