name: KMP Publish Android App on Firebase
on:
  workflow_dispatch:

env:
  GITHUB_ACTION_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

jobs:
  publish_android_app_on_firebase:
    name: Publish Android App on Firebase
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish Android App on Firebase
        uses: ./.github/actions/android-firebase
        with:
          android_package_name: 'mifospay-android'

          keystore_file: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
          keystore_password: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
          key_alias: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS }}
          key_password: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS_PASSWORD }}

          google_services: ${{ secrets.GOOGLESERVICES }}
          firebase_creds: ${{ secrets.FIREBASECREDS }}

          action_url: ${{ env.GITHUB_ACTION_RUN_URL }}




